import { LEVEL_EASY, LEVEL_NORMAL, LEVEL_HARD } from '../constants'

/*
Questions importees et minifiees depuis https://github.com/DimitriMikadze/react-native-game/tree/master/server/questions
*/
const questions = (level) => {
    switch(level){
        case LEVEL_EASY:
            return [{"id":"1","image":"140774802316.jpg","correct":4,"answers":[{"id":"1","answer":"Taylor Lautner"},{"id":"2","answer":"Clive Owen"},{"id":"3","answer":"Russell Crowe"},{"id":"4","answer":"Gerard Butler"}]},{"id":"2","image":"140774179210.jpg","correct":2,"answers":[{"id":"1","answer":"Penélope Cruz"},{"id":"2","answer":"Monica Bellucci"},{"id":"3","answer":"Isabelle Adjani"},{"id":"4","answer":"Salma Hayek"}]},{"id":"3","image":"140774318711.jpg","correct":1,"answers":[{"id":"1","answer":"Benicio Del Toro"},{"id":"2","answer":"Josh Brolin"},{"id":"3","answer":"Clive Owen"},{"id":"4","answer":"Javier Bardem"}]},{"id":"4","image":"14077466871.jpg","correct":2,"answers":[{"id":"1","answer":"Shawn Ashmore"},{"id":"2","answer":"James McAvoy"},{"id":"3","answer":"Josh Helman"},{"id":"4","answer":"Nicholas Hoult"}]},{"id":"5","image":"140750620822.jpg","correct":1,"answers":[{"id":"1","answer":"Melanie Griffith"},{"id":"2","answer":"Michelle Pfeiffer"},{"id":"3","answer":"Dakota Johnson"},{"id":"4","answer":"Goldie Hawn"}]},{"id":"6","image":"140750644426.jpg","correct":4,"answers":[{"id":"1","answer":"Lacey Chabert"},{"id":"2","answer":"Lindsay Lohan"},{"id":"3","answer":"Amanda Seyfried"},{"id":"4","answer":"Rachel McAdams"}]},{"id":"7","image":"140756774559.jpg","correct":1,"answers":[{"id":"1","answer":"Charlton Heston"},{"id":"2","answer":"Burt Lancaster"},{"id":"3","answer":"Gregory Peck"},{"id":"4","answer":"Stephen Boyd"}]},{"id":"8","image":"140756810964.jpg","correct":3,"answers":[{"id":"1","answer":"Jeff Bridges"},{"id":"2","answer":"Ray Stevenson"},{"id":"3","answer":"Christoph Waltz"},{"id":"4","answer":"Daniel Day-Lewis"}]},{"id":"9","image":"14077551475.jpg","correct":4,"answers":[{"id":"1","answer":"Charlize Theron"},{"id":"2","answer":"Jessica Alba"},{"id":"3","answer":"Jennifer Lawrence"},{"id":"4","answer":"Scarlett Johansson"}]},{"id":"10","image":"140756973870.jpg","correct":1,"answers":[{"id":"1","answer":"Elizabeth Banks"},{"id":"2","answer":"Brittany Snow"},{"id":"3","answer":"Jennifer Lawrence"},{"id":"4","answer":"Alison Brie"}]}];
        case LEVEL_NORMAL:
            return [{"id":"1","image":"14077484656.jpg","correct":1,"answers":[{"id":"1","answer":"Catherine Zeta-Jones"},{"id":"2","answer":"Salma Hayek"},{"id":"3","answer":"Mary-Louise Parker"},{"id":"4","answer":"Blake Lively"}]},{"id":"2","image":"140774861324.jpg","correct":4,"answers":[{"id":"1","answer":"Olivia Munn"},{"id":"2","answer":"Amanda Seyfried"},{"id":"3","answer":"Jennifer Morrison"},{"id":"4","answer":"Olivia Wilde"}]},{"id":"3","image":"14077496403.jpg","correct":1,"answers":[{"id":"1","answer":"Ray Liotta"},{"id":"2","answer":"Kevin Costner"},{"id":"3","answer":"Paul Sorvino"},{"id":"4","answer":"Joe Pesci"}]},{"id":"4","image":"140774979018.jpg","correct":4,"answers":[{"id":"1","answer":"Jeremy Irons"},{"id":"2","answer":"Beau Bridges"},{"id":"3","answer":"Lloyd Bridges"},{"id":"4","answer":"Jeff Bridges"}]},{"id":"5","image":"140750581534.jpg","correct":2,"answers":[{"id":"1","answer":"Tasya van Ree"},{"id":"2","answer":"Amber Heard"},{"id":"3","answer":"Connie Nielsen"},{"id":"4","answer":"Vanessa Paradis"}]},{"id":"6","image":"140750657850.jpg","correct":3,"answers":[{"id":"1","answer":"Anne Hathaway"},{"id":"2","answer":"Audrey Tautou"},{"id":"3","answer":"Marion Cotillard"},{"id":"4","answer":"Ellen Page"}]},{"id":"7","image":"140775441680.jpg","correct":1,"answers":[{"id":"1","answer":"Harvey Keitel"},{"id":"2","answer":"Steve Buscemi"},{"id":"3","answer":"Mel Gibson"},{"id":"4","answer":"Harrison Ford"}]},{"id":"8","image":"140757239747.jpg","correct":2,"answers":[{"id":"1","answer":"William Holden"},{"id":"2","answer":"Richard Burton"},{"id":"3","answer":"Michael Wilding"},{"id":"4","answer":"Laurence Olivier"}]},{"id":"9","image":"140775411581.jpg","correct":3,"answers":[{"id":"1","answer":"Clint Eastwood"},{"id":"2","answer":"Dustin Hoffman"},{"id":"3","answer":"Robert Redford"},{"id":"4","answer":"Paul Newman"}]},{"id":"10","image":"140757603382.jpg","correct":4,"answers":[{"id":"1","answer":"Demi Moore"},{"id":"2","answer":"Gina Carano"},{"id":"3","answer":"Gal Gadot"},{"id":"4","answer":"Jordana Brewster"}]}];
        case LEVEL_HARD:
            return [{"id":"1","image":"14077578378.jpg","correct":3,"answers":[{"id":"1","answer":"Penn Dayton Badgley"},{"id":"2","answer":"Jake Gyllenhaal"},{"id":"3","answer":"Jim Sturgess"},{"id":"4","answer":"Nicholas Hoult"}]},{"id":"2","image":"14077475432.jpg","correct":3,"answers":[{"id":"1","answer":"Chris Evans"},{"id":"2","answer":"Sebastian Stan"},{"id":"3","answer":"Tom Hiddleston"},{"id":"4","answer":"Zachary Levi"}]},{"id":"3","image":"140750069376.jpg","correct":3,"answers":[{"id":"1","answer":"Alessandro Costacurta"},{"id":"2","answer":"Paolo Maldini"},{"id":"3","answer":"Gianluigi Buffon"},{"id":"4","answer":"Andrea Pirlo"}]},{"id":"4","image":"140750487513.jpg","correct":1,"answers":[{"id":"1","answer":"Christopher Walken"},{"id":"2","answer":"Clint Eastwood"},{"id":"3","answer":"Al Pacino"},{"id":"4","answer":"Vincent Piazza"}]},{"id":"5","image":"140750607727.jpg","correct":3,"answers":[{"id":"1","answer":"Mila Kunis"},{"id":"2","answer":"Emily Blunt"},{"id":"3","answer":"Hannah Simone"},{"id":"4","answer":"Vincent Piazza"}]},{"id":"6","image":"140750673071.jpg","correct":1,"answers":[{"id":"1","answer":"Emilia Clarke"},{"id":"2","answer":"Sophie Turner"},{"id":"3","answer":"Lena Headey"},{"id":"4","answer":"Tamzin Merchant"}]},{"id":"7","image":"140756583352.jpg","correct":4,"answers":[{"id":"1","answer":"Matt Smith"},{"id":"2","answer":"Michael Fassbender"},{"id":"3","answer":"Tom Hiddleston"},{"id":"4","answer":"Benedict Cumberbatch"}]},{"id":"8","image":"140756712368.jpg","correct":3,"answers":[{"id":"1","answer":"Alex Pettyfer"},{"id":"2","answer":"Cameron Bancroft"},{"id":"3","answer":"Jeremy Irons"},{"id":"4","answer":"Benedict Cumberbatch"}]},{"id":"9","image":"140756744674.jpg","correct":1,"answers":[{"id":"1","answer":"Emma Watson"},{"id":"2","answer":"Emma Stone"},{"id":"3","answer":"Kristen Stewart"},{"id":"4","answer":"Emma Roberts"}]},{"id":"10","image":"140756764553.jpg","correct":4,"answers":[{"id":"1","answer":"Kelly Rutherford"},{"id":"2","answer":"Alexis Bledel"},{"id":"3","answer":"Kristen Bell"},{"id":"4","answer":"Blake Lively"}]}];
        default:
            return;
    } 
};

export const getImagesUri = (level) => {
    return `http://raw.githubusercontent.com/DimitriMikadze/react-native-game/master/server/images/${level}/`;
};

export const getQuestions = (level) => {
    return new Promise((resolve, reject) => {
        let result = resolve(questions(level));
        return result;
    });

};

